credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$lACQiAT5ZISiNMFZHNbeBu8V.P85aMakZexQOd09d7ckdCvb.SS4e
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def
    demo:
      email: demo@gmail.com
      name: Demo User
      password: $2b$12$jfdjdJZHWoFuFFTCh03ZuOgbGUnaUYYBH9UnAzi8122njaJ96Hqwi
    admin:
      email: admin@admin.com
      name: Admin User
      password: $2b$12$GSBab/3Mxy1ylMD/izsY3e5Gjs8NXLs19ikqpVwlm.b3qkUzZQSLS

cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
    - shravanrevanna@gmail.com