[theme]
base= "dark"
primaryColor= "#5A5A5A"
backgroundColor= "#000000"
secondaryBackgroundColor= "#242424"
textColor="#E8E8E8"

#base = "dark"
#primaryColor = "#444444"
#backgroundColor = "#000"
#secondaryBackgroundColor = "#333333"
#textColor = "#fefefe"




#base = "dark"
#primaryColor = "#4D9FEC"
#backgroundColor = "#1B2838"
#secondaryBackgroundColor = "#2A3F55"
#textColor = "#D6E0F0"

#base = "dark"
#primaryColor = "#FF4B4B"
#backgroundColor = "#333333"
#secondaryBackgroundColor = "#444444"
#textColor = "#FFFFFF"